### ISSUE TITLE
API call issue

### ISSUE THREAD

**Issue by JuMayr** [DigitalIO/ComfyUI-stable-wildcards#3]
When i run a ComfyUI Workflow with stable wildcards via the Webinterface, everything works fine.
As soon as I run it via an API call, I get the following error message. No idea how to solve this.

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
File "E:\ComfyUI\execution.py", line 153, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\ComfyUI\execution.py", line 83, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "E:\ComfyUI\execution.py", line 76, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "E:\ComfyUI\custom_nodes\ComfyUI-stable-wildcards\swnodes\StableWildcard.py", line 69, in execute
extras = kwargs['extra']['workflow']['extra']
KeyError: 'extra'

**Comment by DigitalIO** [comment]
Can you please update the node and try again? I don't have comfyui setup to run in API mode so I can't reproduce the issue. I added a few checks that should prevent the error.

**Comment by JuMayr** [comment]
> Can you please update the node and try again? I don't have comfyui setup to run in API mode so I can't reproduce the issue. I added a few checks that should prevent the error.

SOLVED:) THANK YOU
